import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./components/navbar";
import AppSidebar from "./components/sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <NavBar />
        <div style={{ display: 'flex', height: '100vh' }}>
          <AppSidebar />
          <main style={{ 
            flexGrow: 1, 
            height: 'calc(100vh - 64px)', // Full height minus navbar
            marginTop: '64px', // Account for navbar height
            overflow: 'auto'
          }}>
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
